version=1.0.0
group=net.superfeda.sfs_anvil_repair
java_version=21

mod_name=SFsAnvilRepair
mod_author=SuperFeda
mod_id=sfs_anvil_repair
license=MIT
credits=
description=Repair damaged and chipped anvils

minecraft_version=1.21.11
minecraft_version_range=[1.21.11, 1.22)

parchment_minecraft=1.21.11
parchment_version=2025.12.20

fabric_version=0.139.5+1.21.11
fabric_loader_version=0.18.2

neoforge_version=21.11.3-beta
neoforge_loader_version_range=[4,)

neo_form_version=1.21.11-20251209.172050

forgeconfigapiport_version=21.11.1
forgeconfigapiport_version_range=[21.11.0,)

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
